server:
  session-timeout: 900000
  #    tomcat:
  #        max-threads: 1000
  #        min-spare-threads: 30
  port: 6868
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false

bootdo:
  #uploadPath: /Users/dingbaosheng/uploaded_files/
  uploadPath: /www/wwwroot/pics/
  veriCodeNeeded: 0
  username: admin
  password: yisan14
logging:
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.129.219.47:3306/pay_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: pay_db
    password: nyYJxbf6bZawwK5i
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 43.129.219.47
    port: 6379
    password: 383241
    # 连接超时时间（毫秒）
    timeout: 60000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
sell_nofity_url: 123
pay_nofity_url: 123
MERCHANT_NAME: 123
MERCHANT_PRIVATE_KEY: 123
QAPPLE_PUBLIC_KEY: 123
QAPPLE_SERVER_URL: 123
WEB_SITE: 123

ustd:
    gateway: 123
    mchId: 123
    mdkey: 123
    notifyUrl: 123
    withdrawNotifyUrl: 123
